<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DSC 385 - Project 2 Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project2_Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project2_Report_files/libs/quarto-html/quarto.js"></script>
<script src="Project2_Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Project2_Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project2_Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project2_Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project2_Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project2_Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project2_Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project2_Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DSC 385 - Project 2 Report</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="name-and-eid" class="level2">
<h2 class="anchored" data-anchor-id="name-and-eid">Name and EID</h2>
<p>Arshia Riaz - ar65892</p>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>Read in the data with <code>read_csv()</code> and store the data as an R object named <code>dataset</code>. Check the data to make sure all of the expected observations and variables are there.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the data and any necessary packages here.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"maacs.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 150 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): id, gender, mouse_allergic
dbl (7): age, fev1, eNO, cough_days, pm25, no2, mouse

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary and structure</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id                 age            gender               fev1      
 Length:150         Min.   : 5.000   Length:150         Min.   :0.650  
 Class :character   1st Qu.: 7.713   Class :character   1st Qu.:1.370  
 Mode  :character   Median :10.915   Mode  :character   Median :1.870  
                    Mean   :11.215                      Mean   :1.994  
                    3rd Qu.:14.758                      3rd Qu.:2.490  
                    Max.   :17.890                      Max.   :5.000  
                                                        NA's   :17     
      eNO           cough_days          pm25              no2         
 Min.   :  5.00   Min.   : 0.000   Min.   :  0.235   Min.   :  1.459  
 1st Qu.: 17.00   1st Qu.: 1.000   1st Qu.: 13.117   1st Qu.: 14.088  
 Median : 35.00   Median : 2.000   Median : 20.658   Median : 20.694  
 Mean   : 45.71   Mean   : 3.567   Mean   : 27.760   Mean   : 26.669  
 3rd Qu.: 63.00   3rd Qu.: 4.000   3rd Qu.: 35.118   3rd Qu.: 28.507  
 Max.   :210.00   Max.   :14.000   Max.   :198.463   Max.   :235.548  
 NA's   :17                        NA's   :20        NA's   :47       
     mouse         mouse_allergic    
 Min.   :   17.0   Length:150        
 1st Qu.:  316.5   Class :character  
 Median : 1207.5   Mode  :character  
 Mean   : 4444.9                     
 3rd Qu.: 3819.5                     
 Max.   :56846.0                     
 NA's   :34                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 10
$ id             &lt;chr&gt; "fd171e2d", "a66fc33a", "fc038e68", "8e28b8c2", "b2699b…
$ age            &lt;dbl&gt; 14.72, 13.56, 14.50, 13.96, 16.63, 16.56, 17.18, 15.46,…
$ gender         &lt;chr&gt; "male", "female", "male", "female", "female", "female",…
$ fev1           &lt;dbl&gt; 1.78, 2.12, 2.73, 2.36, 3.13, 2.59, 2.60, 3.49, 2.29, 2…
$ eNO            &lt;dbl&gt; 141.0, 68.0, 210.0, 23.0, 18.0, 128.0, 19.0, 26.0, 17.0…
$ cough_days     &lt;dbl&gt; 2, 8, 2, 0, 14, 0, 0, 4, 1, 14, 2, 0, 0, 2, 14, 1, 2, 2…
$ pm25           &lt;dbl&gt; 15.560, 18.890, 17.808, 13.956, 17.864, 43.784, 26.313,…
$ no2            &lt;dbl&gt; NA, 12.827, NA, NA, 30.976, 10.590, NA, 32.902, 25.659,…
$ mouse          &lt;dbl&gt; 2423, 939, 200, NA, 10371, 4789, 760, 264, 419, 187, 10…
$ mouse_allergic &lt;chr&gt; "yes", "yes", "no", "no", "no", "yes", "yes", "no", "no…</code></pre>
</div>
</div>
</section>
</section>
<section id="part-1" class="level2">
<h2 class="anchored" data-anchor-id="part-1">Part 1</h2>
<p>We will first consider the relationship between FEV1 and age. In general, it is expected that as children get older (and hence, larger in size), their FEV1 values should get higher. Verify this by fitting a linear regression model with FEV1 as the outcome and age as a predictor.</p>
<p>How much does FEV1 change for a 1-year increase in the child’s age? (Write your answer below the code block.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fev1 <span class="sc">~</span> age, <span class="at">data =</span> dataset)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fev1 ~ age, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.51099 -0.27100  0.00196  0.23616  2.15477 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.001199   0.134696  -0.009    0.993    
age          0.171162   0.010984  15.583   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4827 on 131 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.6496,    Adjusted R-squared:  0.6469 
F-statistic: 242.8 on 1 and 131 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>FEV1 increases by approximately 0.171 liters per year increase of a child’s age. This pertains to the coefficient of age in the linear regression model. It’s highly significant (p &lt; 2e-16), confirming that older children tend to have higher lung function.This finding aligns with what we would expect biologically, as children’s lung capacity naturally increases as they grow.</p>
</section>
<section id="part-2" class="level2">
<h2 class="anchored" data-anchor-id="part-2">Part 2</h2>
<p>Make a scatterplot of FEV1 on the y-axis and age on the x-axis. Overlay the fitted regression line using the fitted model from Part 1.</p>
<p>How would you characterize the fit of the regression line to the data? Is there anything unexpected in the plot?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> fev1)) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"FEV1 vs Age"</span>, <span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"FEV1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplot shows a clear, strong positive relationship between age and FEV1. The fitted regression line appears to fit the data well, with points distributed fairly evenly around the line.</p>
<p>There are a few unexpected patterns:</p>
<ol type="1">
<li><p>There appears to be more variability in FEV1 values at older ages (&gt;15 years) compared to younger ages</p></li>
<li><p>A few observations at the upper end of the age range have FEV1 values much higher than predicted (&gt;3.5 liters)</p></li>
<li><p>There’s a noticeable cluster of lower-than-expected FEV1 values in the middle age range (approximately 10-13 years)</p></li>
<li><p>The 17 missing FEV1 values could potentially influence the model if they’re not randomly distributed across age groups</p></li>
</ol>
</section>
<section id="part-3" class="level2">
<h2 class="anchored" data-anchor-id="part-3">Part 3</h2>
<p>Make a scatterplot of the fitted values (x-axis) from the regression model and the residuals (y-axis).</p>
<ol type="1">
<li><p>Describe the pattern of the residuals in this plot.</p></li>
<li><p>Recall the assumptions required for making inference from a linear model. Do any of those assumptions appear to be violated?</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>aug1 <span class="ot">&lt;-</span> <span class="fu">augment</span>(model1)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aug1, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs Fitted"</span>, <span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>The residuals seem fairly evenly spread around zero, which supports linear model assumptions. There appears to be slightly more spread in the residuals at higher fitted values, suggesting heteroscedasticity.</li>
<li>No major violations are apparent, but further tests could provide more confidence in our inferences (ex. Shapiro-Wilk test, Q-Q plot)</li>
</ol>
</section>
<section id="part-4" class="level2">
<h2 class="anchored" data-anchor-id="part-4">Part 4</h2>
<p>In previous studies, males have tended to have higher FEV1 values than females. Fit a linear regression model with FEV1 as the outcome and gender as the predictor. <strong>Using the results of the model fit</strong>, answer the following questions:</p>
<ol type="1">
<li><p>On average in this dataset, which gender has higher FEV1 values?</p></li>
<li><p>On average in this dataset, what is the difference in FEV1 values between males and females?</p></li>
</ol>
<p>NOTE: For both of these questions, you are <strong>not</strong> being asked to make a statistical inference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fev1 <span class="sc">~</span> gender, <span class="at">data =</span> dataset)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fev1 ~ gender, data = dataset)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.2334 -0.5734 -0.1825  0.4575  3.1166 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.1325     0.1049  20.327   &lt;2e-16 ***
gendermale   -0.2492     0.1406  -1.772   0.0788 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8058 on 131 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.0234,    Adjusted R-squared:  0.01594 
F-statistic: 3.138 on 1 and 131 DF,  p-value: 0.0788</code></pre>
</div>
</div>
<ol type="1">
<li><p>Females have higher average FEV1 values (2.13 liters) compared to males (1.88 liters)</p></li>
<li><p>The coefficient for gendermale is -0.25, meaning males have 0.25 liters less FEV1 on average compared to females. However, this difference is not statistically significant (p = 0.0788).</p></li>
</ol>
</section>
<section id="part-5" class="level2">
<h2 class="anchored" data-anchor-id="part-5">Part 5</h2>
<p>Now fit a linear regression model with FEV1 as the outcome and gender <em>and</em> age as predictors. Using the results of the model fit, answer the following questions:</p>
<ol type="1">
<li><p>On average in this dataset, which gender has higher FEV1 values when age is held constant?</p></li>
<li><p>On average in this dataset, what is the difference in FEV1 values between males and females, when age is held constant?</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fev1 <span class="sc">~</span> gender <span class="sc">+</span> age, <span class="at">data =</span> dataset)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fev1 ~ gender + age, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.55611 -0.25715  0.00038  0.24088  2.11170 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.06745    0.15692  -0.430    0.668    
gendermale   0.07178    0.08692   0.826    0.410    
age          0.17342    0.01133  15.304   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4833 on 130 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.6514,    Adjusted R-squared:  0.6461 
F-statistic: 121.5 on 2 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li><p>Males have a higher average FEV1 than females when age is held constant</p></li>
<li><p>When controlling for age, males have slightly higher FEV1 values than females by approximately 0.072 liters, though this difference is not statistically significant (p = 0.41).</p></li>
</ol>
</section>
<section id="part-6" class="level2">
<h2 class="anchored" data-anchor-id="part-6">Part 6</h2>
<p>We will now move to looking at the eNO variable.</p>
<ol type="1">
<li>Make a scatterplot of eNO (y-axis) and age (x-axis). Briefly describe the relationship between eNO and age.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> eNO)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"eNO vs Age"</span>, <span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"eNO"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The relationship between exhaled nitric oxide (eNO) and age appears to be positive but weak. The scatterplot shows considerable noise, with eNO values varying greatly across ages.</p>
<ol start="2" type="1">
<li>Fit a linear model with eNO as the outcome and age as the predictor variable. Overlay the fitted regression line on the scatterplot of eNO and age. How would you characterize the quality of the fit of this model? Do any of the linear regression model assumptions appear to be violated?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(eNO <span class="sc">~</span> age, <span class="at">data =</span> dataset)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = eNO ~ age, data = dataset)

Residuals:
   Min     1Q Median     3Q    Max 
-49.29 -26.59 -12.51  19.26 159.13 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  24.0846    10.8416   2.221   0.0280 *
age           1.8475     0.8824   2.094   0.0382 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37.93 on 131 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.03238,   Adjusted R-squared:  0.02499 
F-statistic: 4.384 on 1 and 131 DF,  p-value: 0.03821</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dataset <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> eNO)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"eNO vs Age with Fitted Line"</span>, <span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"eNO"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 17 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The fit appears poor. The relationship between exhaled nitric oxide (eNO) and age is positive but weak (R² ≈ 0.032). Several linear regression assumptions appear to be violated:</p>
<ol type="1">
<li><p>There appears to be a weak relationship between the eNO and age</p></li>
<li><p>There appears to be heteroscedasticity, with greater variability in eNO values at older ages</p></li>
<li><p>Several potential outliers with very high eNO values may have influence on the model</p></li>
<li><p>The weak relationship suggests the linear model may not appropriately capture the underlying pattern</p></li>
</ol>
</section>
<section id="part-7" class="level2">
<h2 class="anchored" data-anchor-id="part-7">Part 7</h2>
<p>Make a histogram of the standardized residuals for the fitted model of eNO and age. Use a few different <code>bin</code> choices in the <code>geom_histogram()</code> function to see how the histogram changes. How would you characterize the shape of the histogram here? Do any of the linear regression model assumptions appear to be violated?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>aug4 <span class="ot">&lt;-</span> <span class="fu">augment</span>(model4)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(aug4, <span class="fu">aes</span>(<span class="at">x =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Standardized Residuals"</span>, <span class="at">x =</span> <span class="st">"Standardized Residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram of standardized residuals from the eNO-age model shows right-skewness, which suggests that linear regression model assumptions appear to be violated. This indicates that the linear model may not be appropriate for modeling eNO without transformation.</p>
</section>
<section id="part-8" class="level2">
<h2 class="anchored" data-anchor-id="part-8">Part 8</h2>
<p>Create a new dataset that replaces eNO with the log of eNO (using the <code>log()</code> function). Store this new dataset in an object called <code>dataset2</code>.</p>
<p>Using <code>dataset2</code>, fit a new linear regression model with the (now log-transformed) eNO variable as the response and age as the predictor.</p>
<ol type="1">
<li><p>Make a plot of the residuals vs.&nbsp;fitted values for this new model (residuals on the y-axis, fitted values on the x-axis).</p></li>
<li><p>Also make a histogram of the standardized residuals from this new model.</p></li>
</ol>
<p>How would you characterize the fit of this model versus the fit of the previous model that did not use the log-transformed eNO variable? Which model is preferable, based on the diagnostic plots you have seen?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dataset2 <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">eNO =</span> <span class="fu">log</span>(eNO))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(eNO <span class="sc">~</span> age, <span class="at">data =</span> dataset2)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model5) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model5) <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>After log-transforming eNO, the residual plots look better, with the distribution of residuals being more symmetrical. This transformation satisfies the normality assumption better than the untransformed model. The log-transformation is preferable for modeling eNO based on the diagnostic plots.</p>
</section>
<section id="part-9" class="level2">
<h2 class="anchored" data-anchor-id="part-9">Part 9</h2>
<p>Create a new dataset that takes the original <code>dataset</code> object and transforms the <code>mouse</code> variable by taking the log transformation of <code>mouse</code>. Store this new dataset in an R object named <code>dataset3</code>.</p>
<p>For this part we will focus on the outcome <code>cough_days</code>. Based on what we know of allergic disease, children should only have a response to mouse allergen if they are in fact allergic to mouse allergen. Let’s examine this hypothesis as follows:</p>
<ol type="1">
<li><p>Create a new dataset called <code>dataset3yes</code> that contains only those individuals in <code>dataset3</code> who have <code>mouse_allergic == "yes"</code>. Using <code>dataset3yes</code>, fit a linear model with <code>cough_days</code> as the outcome and <code>mouse</code> as the predictor.</p></li>
<li><p>Create a new dataset called <code>dataset3no</code> that contains only those individuals in <code>dataset3</code> who have <code>mouse_allergic == "no"</code>. Using <code>dataset3no</code>, fit a linear model with <code>cough_days</code> as the outcome and <code>mouse</code> as the predictor.</p></li>
</ol>
<p>For each analysis, describe what is the relationship between mouse allergen and days with coughing or wheezing (<code>cough_days</code>). Interpret the coefficient for <code>mouse</code> in each of the models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dataset3 <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">mouse =</span> <span class="fu">log</span>(mouse))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dataset3yes <span class="ot">&lt;-</span> dataset3 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mouse_allergic <span class="sc">==</span> <span class="st">"yes"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>dataset3no <span class="ot">&lt;-</span> dataset3 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mouse_allergic <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(cough_days <span class="sc">~</span> mouse, <span class="at">data =</span> dataset3yes)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = cough_days ~ mouse, data = dataset3yes)

Residuals:
   Min     1Q Median     3Q    Max 
-4.475 -2.914 -1.277  1.410 10.447 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   7.2358     2.2672   3.192  0.00225 **
mouse        -0.5084     0.3075  -1.654  0.10344   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.967 on 60 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.04358,   Adjusted R-squared:  0.02764 
F-statistic: 2.734 on 1 and 60 DF,  p-value: 0.1034</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(cough_days <span class="sc">~</span> mouse, <span class="at">data =</span> dataset3no)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = cough_days ~ mouse, data = dataset3no)

Residuals:
   Min     1Q Median     3Q    Max 
-5.520 -3.209 -1.367  1.130 10.882 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   0.1743     2.6902   0.065    0.949
mouse         0.5328     0.3767   1.414    0.163

Residual standard error: 4.695 on 52 degrees of freedom
  (17 observations deleted due to missingness)
Multiple R-squared:  0.03705,   Adjusted R-squared:  0.01853 
F-statistic:     2 on 1 and 52 DF,  p-value: 0.1632</code></pre>
</div>
</div>
<ol type="1">
<li><p>For mouse-allergic children (dataset3yes), the coefficient for log(mouse) is -0.51 (p=0.10), suggesting that each unit increase in log(mouse allergen) is associated with approximately 0.5 fewer cough days, though this doesn’t reach statistical significance.</p></li>
<li><p>For non-allergic children (dataset3no), the coefficient is 0.53 (p=0.16), indicating the opposite relationship - each unit increase in log(mouse allergen) is associated with 0.5 more cough days.</p></li>
</ol>
<p>These relationships, although not statistically significant, support that allergic individuals may develop tolerance with continued exposure, while non-allergic individuals might experience non-specific irritant effects at higher exposure levels. The R² values (0.044 and 0.037) indicate that mouse allergen levels explain only a small portion of the variation in cough days.</p>
</section>
<section id="part-10" class="level2">
<h2 class="anchored" data-anchor-id="part-10">Part 10</h2>
<p>Make a scatterplot of <code>cough_days</code> (y-axis) and <code>mouse</code> (x-axis), with a separate panel for those who are not mouse allergic and those who are mouse allergic (you can use <code>facet_wrap()</code> for this) using <code>dataset3</code>. In each plot, overlay the linear regression line fit using <code>geom_smooth(method = "lm")</code>.</p>
<p>Are the relationships shown in the plots what you would have expected to see given what we know about allergic disease?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>dataset3 <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mouse, <span class="at">y =</span> cough_days)) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>mouse_allergic) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cough Days vs Mouse Allergen by Allergy Status"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 34 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 34 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplots confirm these opposing relationships: a downward slope for allergic children and an upward slope for non-allergic children. The confidence bands around the regression lines are wide, reflecting the uncertainty in these associations. Individual data points show considerable scatter, explaining the non-significant findings. This pattern makes biological sense - allergic children may react more to mouse allergen exposure, resulting in more cough days as allergen levels increase.</p>
</section>
<section id="part-11" class="level2">
<h2 class="anchored" data-anchor-id="part-11">Part 11</h2>
<p>Using the <code>dataset3</code> object, fit a linear regression model with FEV1 as the outcome and age, gender, PM2.5, NO2, mouse allergen, and mouse allergic status as the predictors in the model. Compute 95% confidence intervals for each of the coefficients in the model.</p>
<p>If we were going to collect data on a much larger sample of children, which of the three indoor pollutants—PM2.5, NO2, or mouse allergen—would most likely have a relationship similar to the one that we observe in this dataset?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>model8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fev1 <span class="sc">~</span> age <span class="sc">+</span> gender <span class="sc">+</span> pm25 <span class="sc">+</span> no2 <span class="sc">+</span> mouse <span class="sc">+</span> mouse_allergic, <span class="at">data =</span> dataset3)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fev1 ~ age + gender + pm25 + no2 + mouse + mouse_allergic, 
    data = dataset3)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.29134 -0.24441 -0.01134  0.22070  1.29394 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -0.685952   0.314583  -2.181   0.0329 *  
age                0.200278   0.015965  12.544   &lt;2e-16 ***
gendermale         0.175940   0.115081   1.529   0.1312    
pm25               0.001328   0.002216   0.599   0.5510    
no2                0.004314   0.001718   2.510   0.0146 *  
mouse              0.036696   0.031825   1.153   0.2532    
mouse_allergicyes -0.278733   0.112400  -2.480   0.0158 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4683 on 64 degrees of freedom
  (79 observations deleted due to missingness)
Multiple R-squared:  0.7505,    Adjusted R-squared:  0.7271 
F-statistic: 32.08 on 6 and 64 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %       97.5 %
(Intercept)       -1.3144046484 -0.057499300
age                0.1683834095  0.232172723
gendermale        -0.0539616775  0.405841405
pm25              -0.0030981190  0.005754459
no2                0.0008807409  0.007746905
mouse             -0.0268822732  0.100273453
mouse_allergicyes -0.5032778879 -0.054187667</code></pre>
</div>
</div>
<p>In the full model with multiple predictors, NO2 shows the most consistent relationship with FEV1. The 95% confidence interval for NO2 (0.0009 to 0.0077) doesn’t include zero, suggesting it would likely show a similar relationship in a larger sample. PM2.5 and mouse allergen have confidence intervals that include zero.</p>
</section>
<section id="part-12" class="level2">
<h2 class="anchored" data-anchor-id="part-12">Part 12</h2>
<p>Make a scatterplot of the residuals versus the fitted values from this model. Describe what you see in the residuals and if there are any violations of the linear regression model assumptions evident in the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model8) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs Fitted Values"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project2_Report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residual vs.&nbsp;fitted values plot shows that the residuals are centered around zero with no observable pattern, suggesting that the linear model is appropriate. However, there is some heteroscedasticity in the residuals, with larger residuals observed at higher fitted values. This suggests that the model is less accurate at predicting FEV1 for older children.</p>
</section>
<section id="part-13" class="level2">
<h2 class="anchored" data-anchor-id="part-13">Part 13</h2>
<p>Identify the observations with the two largest residuals in absolute value. How would you describe these two children and why do you think they have such large residuals from the model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Add your code here</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(model8) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">abs_resid =</span> <span class="fu">abs</span>(.resid)) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(abs_resid, <span class="at">n =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 15
  .rownames  fev1   age gender  pm25   no2 mouse mouse_allergic .fitted .resid
  &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
1 15         5     16.6 male    39.3 124.   8.17 no                3.71   1.29
2 35         1.67  17.6 female  28.5  21.7  7.24 yes               2.96  -1.29
# ℹ 5 more variables: .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;,
#   .std.resid &lt;dbl&gt;, abs_resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The two observations with the largest residuals represent the following:</p>
<ol type="1">
<li><p>A 16.6-year-old male with FEV1 of 5.0 liters, much higher than the model’s prediction of 3.71 liters (residual = +1.29 liters). This child may have exceptionally well-developed lungs, perhaps due to physical activity or genetic factors not captured in our model.</p></li>
<li><p>A 17.6-year-old female with FEV1 of only 1.67 liters, substantially lower than the model’s prediction of 2.96 liters (residual = -1.29 liters). This child may have compromised lung function due to a respiratory condition or there might have been a measurement error.</p></li>
</ol>
<p>These outliers suggest that individual variation in respiratory health could still be present even after accounting for multiple predictors.</p>
</section>
<section id="part-14" class="level2">
<h2 class="anchored" data-anchor-id="part-14">Part 14</h2>
<p>Suppose you had the ability to improve the fit of the model by collecting data on a new variable. What data would you most like to collect to improve this model? Why?</p>
<p>To improve this model, collecting data on height and weight (or BMI) could be valuable, as these measurements have strong physiological relationships with lung function. Lung capacity is directly related to body size. This could potentially address the outlier cases we identified by accounting for their body proportions. Additionally, these measurements would help control for confounding that may otherwise conceal the relationships between environmental exposures and lung function.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>